exec("./debug/init.cs");
exec("./effects.cs");
exec("./weapon_base.cs");
//Sharp
exec("./weapon_dagger.cs");
exec("./weapon_shortsword.cs");
exec("./weapon_longsword.cs");
exec("./weapon_spear.cs");
exec("./weapon_machete.cs");
//Blunt
exec("./weapon_mace.cs");
//Weirdness
exec("./lightsaber/server.cs");